FROM node:20-alpine AS build

WORKDIR /app

COPY src/frontend/package.json ./package.json
COPY src/frontend/eslint.config.js ./eslint.config.js
RUN npm install

COPY src/frontend/ .
RUN npm run build

FROM nginx:1.27-alpine

COPY src/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
